import { NextRequest } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
export const dynamic = "force-dynamic";

/**
 * GET /api/metadata/[tokenId]/image?v=VERSION
 * Redirects to the pre-generated image in Supabase Storage.
 * The ?v= param is a cache-buster so OpenSea always fetches fresh.
 * No Sharp compositing here — image was pre-generated by /api/generate-image.
 */
export async function GET(_req: NextRequest, { params }: { params: { tokenId: string } }) {
  const tokenId = Number(params.tokenId);

  const { data: rows } = await supabase
    .from("token_images")
    .select("image_url")
    .eq("token_id", tokenId)
    .limit(1);

  const imageUrl = rows?.[0]?.image_url;

  if (!imageUrl) {
    return new Response("Image not found", { status: 404 });
  }

  // Redirect to the actual Supabase Storage URL
  return Response.redirect(imageUrl, 302);
}
